# Site settings
title: "TABLE books pro"
description: "Table books pro is an independent publisher of unique table books, slim volumes, and more. Better Coffee Table Books."
url: "https://tablebooks.pro"
baseurl: ""
email: "tablebookspro@protonmail.com"
lang: "en-US"
timezone: "America/New_York"
date_format: "%b %-d, %Y"

# Build settings
markdown: kramdown

permalink: pretty
safe: false # Explicitly allow plugins

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files
exclude:
  - README.md