# Site settings
title: "TABLE books pro"
description: "TABLE books pro is an independent publisher of edge-printed coffee table books, slim volumes, and unique monographs. The books that decorate our tables and bookshelves should be beautiful and imbued with meaning.<br><br>Our ever-expanding catalogue currently contains Bitcoin Coffee Table Book and SUN by D.H. Lawrence. American Coffee Table Book is coming soon and can be pre-ordered online thru book retailers worldwide."
url: "https://tablebooks.pro"
baseurl: ""
email: "tablebookspro@protonmail.com"
lang: "en-US"
timezone: "America/New_York"
date_format: "%b %-d, %Y"

# SEO, OG, Etc.
jekyll-seo-tag:
  static_image: /assets/img/logo/table-book-og-logo.jpg

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/logo/table-book-og-logo.jpg

# Social profiles (optional, for social meta tags)
twitter:
  username: tablebookspro
facebook:
  username: tablebookspro
author:
  name: TABLE books pro
  email: tablebookspro@protonmail.com
  twitter: tablebookspro

# Build settings
markdown: kramdown

permalink: pretty

# Exclude files
exclude:
  - drafts/
  - private/
  - README.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

sitemap:
  priorities:
    "/": 1.0
    "/books/american/": 1.0
    "/books/bitcoin/": 1.0
    "/books/": 0.5
    "/about/": 0.5
    "/contact/": 0.5
    "/blog/": 0.2
    "/privacy/": 0.2
    "/terms-of-service/": 0.2
    "/disclosure/": 0.2