# Site settings
title: TableBooks Pro
description: A professional website for TableBooks
url: "https://tablebookspro.github.io"
baseurl: "/tablebooks.pro"
logo: "/assets/images/logo.svg"
social:
  twitter: "https://twitter.com/tablebooks"
  facebook: "https://facebook.com/tablebooks"
email: "contact@tablebooks.pro"
phone: "+1-555-123-4567"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock