title: TABLE books pro
description: "Independent publisher of unique table books, chapbooks, and more."
baseurl: "/tablebooks.pro"
url: "https://tablebookspro.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: pretty

lang: "en-US"
timezone: "America/New_York"
date_format: "%b %-d, %Y"

email: "tablebookspro@protonmail.com"