title: TABLE books pro
description: "Table books pro ia an independent publisher of unique table books, slim volumes, and more. Better Coffee Table Books."
baseurl: "/tablebooks.pro"
url: "https://tablebooks.pro"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: pretty

lang: "en-US"
timezone: "America/New_York"
date_format: "%b %-d, %Y"

email: "tablebookspro@protonmail.com"

exclude:
  - README.md