# Site settings
title: TABLE Books Pro
description: "Table Books Pro is an independent publisher of unique table books, slim volumes, and more. Better Coffee Table Books."
url: "https://tablebooks.pro"
baseurl: ""
email: "tablebookspro@protonmail.com"
lang: "en-US"
timezone: "America/New_York"
date_format: "%b %-d, %Y"

# Build settings
markdown: kramdown
theme: minima
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - README.md